name: "Upload Beta (1GP)"
description: "Upload a 1GP managed beta package version"
inputs:
  jwt-private-key:
    type: string
    required: True
  connected-app-client-id:
    type: string
    required: True
  username:
    type: string
    required: True
  instance-url:
    type: string
    required: True
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: "Run CumulusCI Flow: ci_master"
      uses: cumulusci-actions/execute-cumulusci-flow@main
      with:
        org-name: packaging
        flow-name: ci_master
      env:
        CUMULUSCI_ORG_packaging: '{"username": "${{ inputs.username }}", "instance_url": "${{ inputs.instance-url }}"}'
        SFDX_CLIENT_ID: '${{ inputs.connected-app-client-id }}'
        SFDX_HUB_KEY: '${{ inputs.jwt-private-key }}'
    - name: "Run CumulusCI Flow: release_beta"
      uses: cumulusci-actions/execute-cumulusci-flow@main
      with:
        org-name: packaging
        flow-name: release_beta
      env:
        CUMULUSCI_ORG_packaging: '{"username": "${{ inputs.username }}", "instance_url": "${{ inputs.instance-url }}"}'
        SFDX_CLIENT_ID: '${{ inputs.connected-app-client-id }}'
        SFDX_HUB_KEY: '${{ inputs.jwt-private-key }}'
