name: "Upload Beta (1GP)"
description: "Upload a 1GP managed beta package version"
inputs:
  packaging-auth-url:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: cumulusci-actions/setup-cumulus@main
    - uses: cumulusci-actions/authorize-org@main
      with:
          auth-url: '${{ inputs.packaging-auth-url }}'
          org-name: packaging
    - name: "Run CumulusCI Flow: ci_master"
      uses: cumulusci-actions/run-flow@main
      with:
        org-name: packaging
        flow-name: ci_master
    - name: "Run CumulusCI Flow: release_beta"
      uses: cumulusci-actions/run-flow@main
      with:
        org-name: packaging
        flow-name: release_beta
